ALTER TABLE tasks ADD COLUMN due_at TIMESTAMPTZ NULL;
ALTER TABLE tasks ADD COLUMN assignee_id VARCHAR(36) NULL;
ALTER TABLE tasks ADD COLUMN enable_notice BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE tasks ADD COLUMN reminder_at TIMESTAMPTZ NULL;
ALTER TABLE tasks ADD COLUMN type_reminder INTEGER NOT NULL DEFAULT 0;