DROP TABLE IF EXISTS jti_sessions;
-- DROP TABLE IF EXISTS order_infos;
-- DROP TABLE IF EXISTS payments;
-- DROP TABLE IF EXISTS inventories;
-- DROP TABLE IF EXISTS order_items;
-- DROP TABLE IF EXISTS orders;
-- DROP TABLE IF EXISTS staff;
-- DROP TABLE IF EXISTS products;
-- DROP TABLE IF EXISTS categories;
-- DROP TABLE IF EXISTS customers;
-- DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS accounts;
-- DROP TABLE IF EXISTS messages;
